//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapsXF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapsXF.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map name.
        /// </summary>
        internal static string Create_Map_Name {
            get {
                return ResourceManager.GetString("Create_Map_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download area.
        /// </summary>
        internal static string Download_Region {
            get {
                return ResourceManager.GetString("Download_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Gen_About {
            get {
                return ResourceManager.GetString("Gen_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Gen_Cancel {
            get {
                return ResourceManager.GetString("Gen_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Gen_Clear {
            get {
                return ResourceManager.GetString("Gen_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Gen_Close {
            get {
                return ResourceManager.GetString("Gen_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Gen_Delete {
            get {
                return ResourceManager.GetString("Gen_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download map failed.
        /// </summary>
        internal static string Gen_Download_Map_Failed {
            get {
                return ResourceManager.GetString("Gen_Download_Map_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download offline map.
        /// </summary>
        internal static string Gen_Download_Offline_Map {
            get {
                return ResourceManager.GetString("Gen_Download_Offline_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline maps.
        /// </summary>
        internal static string Gen_Downloaded_Maps {
            get {
                return ResourceManager.GetString("Gen_Downloaded_Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        internal static string Gen_Draw {
            get {
                return ResourceManager.GetString("Gen_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw an area to download.
        /// </summary>
        internal static string Gen_Draw_Area_To_Download {
            get {
                return ResourceManager.GetString("Gen_Draw_Area_To_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometries.
        /// </summary>
        internal static string Gen_Geometries {
            get {
                return ResourceManager.GetString("Gen_Geometries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Gen_Loading {
            get {
                return ResourceManager.GetString("Gen_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location options.
        /// </summary>
        internal static string Gen_LocationOptions {
            get {
                return ResourceManager.GetString("Gen_LocationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Gen_Log {
            get {
                return ResourceManager.GetString("Gen_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Gen_Map {
            get {
                return ResourceManager.GetString("Gen_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        internal static string Gen_Measure {
            get {
                return ResourceManager.GetString("Gen_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Gen_Name {
            get {
                return ResourceManager.GetString("Gen_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Gen_No {
            get {
                return ResourceManager.GetString("Gen_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Gen_Off {
            get {
                return ResourceManager.GetString("Gen_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Gen_Ok {
            get {
                return ResourceManager.GetString("Gen_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string Gen_On {
            get {
                return ResourceManager.GetString("Gen_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Gen_Search {
            get {
                return ResourceManager.GetString("Gen_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Gen_Send {
            get {
                return ResourceManager.GetString("Gen_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show offline maps.
        /// </summary>
        internal static string Gen_Show_Downloaded_Offline_Maps {
            get {
                return ResourceManager.GetString("Gen_Show_Downloaded_Offline_Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all geometries?.
        /// </summary>
        internal static string Gen_Sure_Remove_All_Geometries {
            get {
                return ResourceManager.GetString("Gen_Sure_Remove_All_Geometries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all offline maps?.
        /// </summary>
        internal static string Gen_Sure_Remove_All_Offline_Map {
            get {
                return ResourceManager.GetString("Gen_Sure_Remove_All_Offline_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete geometry?.
        /// </summary>
        internal static string Gen_Sure_Remove_Geometry {
            get {
                return ResourceManager.GetString("Gen_Sure_Remove_Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete offline map?.
        /// </summary>
        internal static string Gen_Sure_Remove_Offline_Map {
            get {
                return ResourceManager.GetString("Gen_Sure_Remove_Offline_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Gen_Yes {
            get {
                return ResourceManager.GetString("Gen_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection and try again..
        /// </summary>
        internal static string GenErr_CheckYourNetworkMessage {
            get {
                return ResourceManager.GetString("GenErr_CheckYourNetworkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service requires you to be online..
        /// </summary>
        internal static string GenErr_NoNetworkMessage {
            get {
                return ResourceManager.GetString("GenErr_NoNetworkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string GenErr_NoNetworkTitle {
            get {
                return ResourceManager.GetString("GenErr_NoNetworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass.
        /// </summary>
        internal static string Gps_Compass {
            get {
                return ResourceManager.GetString("Gps_Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        internal static string Gps_Navigation {
            get {
                return ResourceManager.GetString("Gps_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re center.
        /// </summary>
        internal static string Gps_ReCenter {
            get {
                return ResourceManager.GetString("Gps_ReCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure area.
        /// </summary>
        internal static string Measure_Area {
            get {
                return ResourceManager.GetString("Measure_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure length.
        /// </summary>
        internal static string Measure_Lenght {
            get {
                return ResourceManager.GetString("Measure_Lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing map name.
        /// </summary>
        internal static string Missing_Map_Name {
            get {
                return ResourceManager.GetString("Missing_Map_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use this function the app needs access to:.
        /// </summary>
        internal static string Permission_Message {
            get {
                return ResourceManager.GetString("Permission_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings?.
        /// </summary>
        internal static string Permission_Settings {
            get {
                return ResourceManager.GetString("Permission_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access for:.
        /// </summary>
        internal static string Permission_Title {
            get {
                return ResourceManager.GetString("Permission_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basemap.
        /// </summary>
        internal static string Select_Basemap {
            get {
                return ResourceManager.GetString("Select_Basemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select color.
        /// </summary>
        internal static string Select_Color {
            get {
                return ResourceManager.GetString("Select_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select geometry.
        /// </summary>
        internal static string Select_Geometry {
            get {
                return ResourceManager.GetString("Select_Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select GPS settings.
        /// </summary>
        internal static string Select_Gps_Settings {
            get {
                return ResourceManager.GetString("Select_Gps_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden map.
        /// </summary>
        internal static string Select_Sweden_Basemap {
            get {
                return ResourceManager.GetString("Select_Sweden_Basemap", resourceCulture);
            }
        }
    }
}
